### ISSUE TITLE
app.py different from windows exe?

### ISSUE THREAD

**Issue by nexuslux** [KindOPSTAR/QualiGPT#1]
This is an exciting project. Curious if the latest version that was compiled in the windows exe file you shared is different from the qualigptapp.py code that is shared?

Reason is that when I use the code version, it seems there is an error with the openai api handling - a couple of months back OpenAi changed how they handle the api and I keep getting that message that it should be updated.

Thanks!

**Comment by KindOPSTAR** [comment]
Thank you for your interest in this project, and thank you for reporting this error. I apologize for the late response due to being busy with work recently, but I will follow up and fix any potential issues soon. I think you are right, this may be due to OpenAI changing the way they handle their API, but this is expected to be a solvable problem! Thanks again!

**Comment by nexuslux** [comment]
Thanks for the response Albert! Very cool project, feel like it would benefit some of my use cases tremendously. No rush on any updates... just thought id point out ;)

**Comment by KindOPSTAR** [comment]
Hi Tristan, 

Thanks for waiting, just a friendly reminder, I've updated the QualiGPT to version v0.1.1-alpha. Although it might still not be perfect, the issues have finally been resolved. You can download .exe file to text at [QualiGPT-v0.1.1-alpha](https://github.com/KindOPSTAR/QualiGPT/releases/tag/QualiGPT-v0.1.1-alpha) now. Thank you for your support! 

Best wishes!
