### ISSUE TITLE
"invalid api key" on mac?

### ISSUE THREAD

**Issue by jcemminger** [KindOPSTAR/QualiGPT#3]
I just downloaded the latest release, and the app launches but when I enter the API key that I just created in openai, it says "API Key is invalid. You are now in Testing mode."

Any suggestions?

**Comment by KindOPSTAR** [comment]
Hi jcemminger,

Thank you for your interest about QualiGPT. I have released a [new version](https://github.com/KindOPSTAR/QualiGPT/releases/tag/QualiGPT-v0.1.1-alpha) that you can try out (although it may not be perfect). Over the past few months, OpenAI seems to have updated their API protocol, and the issue may be related to this. Additionally, since this is still a test version, please set a usage limit for your API key to avoid excessive use. Please let me know if you have any questions.

Thank you very much!
